### ISSUE TITLE
关于ST7789demo的问题

### ISSUE THREAD

**Issue by shenzh4180428** [funnygeeker/micropython-easydisplay#1]
大佬您好，我用esp32s3n16r8的板子+st7789驱动的lcd屏幕无法显示内容，能提供一下st7789驱动的demo吗？

**Comment by funnygeeker** [comment]
```python
# 这是一个使用示例 This is an example of usage
import time
from machine import SPI, Pin
from driver import st7789_buf
from lib.easydisplay import EasyDisplay

# ESP32S3 & ST7789
spi = SPI(1, baudrate=20000000, polarity=0, phase=0, sck=Pin(18), mosi=Pin(17))
dp = st7789_buf.ST7789(width=240, height=240, spi=spi, cs=14, dc=15, res=16, rotate=1, bl=13)
ed = EasyDisplay(display=dp, font="/text_lite_16px_2312.v3.bmf", show=True, color=0xFFFF, clear=True,
                 color_type="RGB565")

ed.text("你好，世界！\nHello World!\nこんにちは、世界！", 0, 0)
```
- 备注：由于近期放假回家，硬件不完善，上述代码未经实际硬件测试，仅供参考

1. 如果初始化时未指定 `show=True`，则可能需要你进行手动 ed.show() 将缓冲区的内容刷新到屏幕（仅适用于有缓冲的buf驱动，无缓冲区的驱动不需要进行刷新）
2. 如果出现  `MemoryError`，可以尝试更换驱动为 `st7789_spi`
3. 如果无法正常进行显示，请检查字体文件是否正常加载

如果需要更详细的解答，请尽可能提供硬件接线情况，用于开发硬件的实拍图片，测试用的原始代码以及报错信息，以方便判断问题，祝您生活愉快。

**Comment by shenzh4180428** [comment]
还是不行，没有任何报错，屏幕就是不显示。
![WechatIMG1075](https://github.com/funnygeeker/micropython-easydisplay/assets/26451875/60d47ad0-8f40-468e-a76b-0f19fb1208ea)
![WechatIMG1074](https://github.com/funnygeeker/micropython-easydisplay/assets/26451875/7abf77d0-fc9f-43ba-a500-aa59606d3bad)

**Comment by funnygeeker** [comment]
该问题已私聊进行解决，更换了标准的ST7789屏幕，效果显著。。。
